df <- read.table('household_power_consumption.txt', header = T, sep = ';', stringsAsFactors = F, na.strings = '?', skip = 66636, nrow = 2880)
colnames(df) <- c('Date', 'Time', 'Global_active_power', 'Global_reactive_power', 'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3')
datetime <- strptime(paste(df$Date, df$Time, sep = ' '), format = '%d/%m/%Y %H:%M:%S')
df <- data.frame(datetime, df[,3:3])
colnames(df) <- c('datetime', 'Global_Active_power')
png('plot2.png', bg = 'transparent')
with(df, plot(datetime, Global_Active_power, type = 'l', ylab = 'Global Active Power (kilowatts)', xlab = ''))
dev.off()
